### PR TITLE
Recommended MET filters added in PatUtils.

### PR DESCRIPTION
**Pull request by vischia**
Dear All,

I followed the latest recommendations from the MET POG in order to implement the recommended MET filters in our code. 

You can find the two addional functions in PatUtils.h/cc.
You will need to use them in the way exemplified in bin/chhiggs/runAnalysis.cc.
For data, you will need to run on a mixture of PromptReco and 17Jul15 ReReco MiniAODs: one of the PatUtils functions takes care of selecting the proper orthogonal mix. My data/chhiggs/xsec_samples.json contains the paths for the PromptReco and 17Jul15 samples for a few data PDs: the full list is  https://cmsweb.cern.ch/das/request?view=plain&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*2015B*17Jul2015*%2FMINIAOD

Please let me know if you find any issue :) In the MET filter function there is some additional documentation. 

Cheers,
Pietro

### CODE REVIEW

**Comment by laramaktub** [comment]
Thanks Pietro! :)

**Comment by vischia** [comment]
You are welcomeeee :)

It may change a bit, by the way: in the HyperNews discussion linked in the commit message of d4b866b I have still one pending question about the logic of the filter),

Cheers,
Pietro

**Comment by vischia** [comment]
OK, actually, Loic: 

In storeTools.py, function keepOnlyFilesFromGoodRun you replaced the das_client check for the run number with a check based on file name parsing.

This worked because for PromptReco the files are like: /store/data/Run2015B/SingleMu/MINIAOD/PromptReco-v1/000/250/987/00000/787E4EA9-A525-E511-9647-02163E011DE5.root
where /250/987/ encodes the run number.

The problem is that the MiniAOD ReReco filenames are of the type:
 /store/data/Run2015B/SingleMu/MINIAOD/17Jul2015-v1/30000/2A451E44-BE2E-E511-AFBA-0025905A613C.root

I had circumvented the problem by re-enabling das_client query (and forgot to commit it :P ), but I understand that this is not optimal.

What I can do is to have the das_client query enabled only for files containing "17Jul15" in the file name path, so that for PromptReco the method is still the filename parsing, and then commit the modifications and do a pull request.

Would you be OK with that?

Cheers,
Pietro

**Comment by vischia** [comment]
Anyways, you may want to follow this thread: https://hypernews.cern.ch/HyperNews/CMS/add-response.pl/physTools/3383.html

**Comment by quertenmont** [comment]
The problem with the das_client check  (you'll realise it veyr quickly),
is that we need to make a request for every single file and that takes a lot of time.

What I would do is simply disable the run check in case the run pattern is not found in the file name.
That would work for whatever samples (without any adhoc filtering)

What do you think?

Loic

**Comment by quertenmont** [comment]
just as a reminder, there is anyway a Lumi/Run filtering done within in the job,
so this initial run filtering is just there to submit less jobs on the cluster... nothing more

Loic

**Comment by vischia** [comment]
AHA!

That's true.

I'm fine with the proposal :)

Anyways, it will be nice to know what the plans are for next generation of
miniAODs, because when the data will grow large it would be a severe bonus
to be able to submit less jobs on the cluster!

Thanks!
Cheers,
Pietro


2015-07-29 18:34 GMT+01:00 Loic Quertenmont <notifications@github.com>:

> just as a reminder, there is anyway a Lumi/Run filtering done within in
> the job,
> so this initial run filtering is just there to submit less jobs on the
> cluster... nothing more
>
> Loic
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quertenmont/2l2v_fwk/pull/36#issuecomment-126029949>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Pull request merged**
