### PR TITLE
Separate JEC payloads for 50 and 25 ns, and reactivated iihe line for batch

### PR DESCRIPTION
**Pull request by vischia**
Hi,

I reactivated the batch line for iihe (but still have to figure out why does it break the submission at LIP), and added the payloads for 50 and 25 ns in different directories.
data/jec/50ns
data/jec/25ns

Please take note of the fact that the naming scheme of the files inside the two directories is the same, but in your executable BEFORE RUNNING NEXT TIME YOU MUST UPDATE the input directory name :)

The old files in jec/  have been removed for clarity.

Cheers,
Pietro

### CODE REVIEW

**Comment by vischia** [comment]
There is also a data/jec/jecTags.txt that lists for 50 and 25 ns the name of the JEC that is contained in the respective directories, to keep track of which version are we using ;)

**Comment by vischia** [comment]
Hi All,

so, it is not and will not be contained in this pull request, but I am modifying the pileup treatment to have always doubles and array of doubles instead of floats and arrays of floats.

Do you agree? I can leave a duplicate function using floats, with a compilation warning, if you want, for a while.

Please let me know a.s.a.p.

Cheers,
Pietro

**Comment by quertenmont** [comment]
Why this change?

Loic

**Comment by vischia** [comment]
Hi Loic,

I had already precision problems with histograms when using floats, and I
am concerned by the low values of the bin content of pileup histograms.

Cheers,
Pietro

2015-09-15 17:05 GMT+02:00 Loic Quertenmont <notifications@github.com>:

> Why this change?
>
> Loic
> On Sep 15, 2015 4:34 PM, "Pietro Vischia" <notifications@github.com>
> wrote:
>
> > Hi All,
> >
> > so, it is not and will not be contained in this pull request, but I am
> > modifying the pileup treatment to have always doubles and array of
> doubles
> > instead of floats and arrays of floats.
> >
> > Do you agree? I can leave a duplicate function using floats, with a
> > compilation warning, if you want, for a while.
> >
> > Please let me know a.s.a.p.
> >
> > Cheers,
> > Pietro
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140413240
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140422561>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by quertenmont** [comment]
I really doubt that we are affected by float vs double precision here,
but I don't have any concern if you change from float to double, as soon as
the true pileupreweighter works fine with double.  (please check)

Loic

2015-09-15 17:33 GMT+02:00 Pietro Vischia <notifications@github.com>:

> Hi Loic,
>
> I had already precision problems with histograms when using floats, and I
> am concerned by the low values of the bin content of pileup histograms.
>
> Cheers,
> Pietro
>
> 2015-09-15 17:05 GMT+02:00 Loic Quertenmont <notifications@github.com>:
>
> > Why this change?
> >
> > Loic
> > On Sep 15, 2015 4:34 PM, "Pietro Vischia" <notifications@github.com>
> > wrote:
> >
> > > Hi All,
> > >
> > > so, it is not and will not be contained in this pull request, but I am
> > > modifying the pileup treatment to have always doubles and array of
> > doubles
> > > instead of floats and arrays of floats.
> > >
> > > Do you agree? I can leave a duplicate function using floats, with a
> > > compilation warning, if you want, for a while.
> > >
> > > Please let me know a.s.a.p.
> > >
> > > Cheers,
> > > Pietro
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140413240
> > >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140422561
> >.
> >
>
>
>
> --
> Pietro Vischia
> LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> Portugal
> mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> office: 00351 21 799 5017
> mail: pietro.vischia@gmail.com
> skype: rambling_hadron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140433990>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by vischia** [comment]
OK :)

Anyways you can in the meantime safely merge this, which fixes the issue
for iihe and has the 25 and 50 ns payloads :)

2015-09-15 17:47 GMT+02:00 Loic Quertenmont <notifications@github.com>:

> I really doubt that we are affected by float vs double precision here,
> but I don't have any concern if you change from float to double, as soon as
> the true pileupreweighter works fine with double. (please check)
>
> Loic
>
>
> 2015-09-15 17:33 GMT+02:00 Pietro Vischia <notifications@github.com>:
>
> > Hi Loic,
> >
> > I had already precision problems with histograms when using floats, and I
> > am concerned by the low values of the bin content of pileup histograms.
> >
> > Cheers,
> > Pietro
> >
> > 2015-09-15 17:05 GMT+02:00 Loic Quertenmont <notifications@github.com>:
> >
> > > Why this change?
> > >
> > > Loic
> > > On Sep 15, 2015 4:34 PM, "Pietro Vischia" <notifications@github.com>
> > > wrote:
> > >
> > > > Hi All,
> > > >
> > > > so, it is not and will not be contained in this pull request, but I
> am
> > > > modifying the pileup treatment to have always doubles and array of
> > > doubles
> > > > instead of floats and arrays of floats.
> > > >
> > > > Do you agree? I can leave a duplicate function using floats, with a
> > > > compilation warning, if you want, for a while.
> > > >
> > > > Please let me know a.s.a.p.
> > > >
> > > > Cheers,
> > > > Pietro
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140413240
> > > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140422561
> > >.
> > >
> >
> >
> >
> > --
> > Pietro Vischia
> > LIP-Lisboa Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
> > Portugal
> > mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
> > office: 00351 21 799 5017
> > mail: pietro.vischia@gmail.com
> > skype: rambling_hadron
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140433990
> >.
> >
>
>
>
> --
> ---------------------------------------------------------
> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
> experiment
> Office CERN : bldg.40, RB-08
> Phone CERN : +41 2276 71548
> Mobile BE : +32 474 831531
> WWW : http://www.fynu.ucl.ac.be/users/l.quertenmont/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/quertenmont/2l2v_fwk/pull/49#issuecomment-140437929>.
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Pull request merged**
